#!/bin/bash
clear

# color code
L=$(tput bold)
R=$(tput setaf 1)
G=$(tput setaf 2)
B=$(tput setaf 33)
N=$(tput sgr0)

echo "${G}${L}[+] Optional steps  ......${N}"

# autologin
echo "${B}${L}[+] Do you want to enable lxdm autologin  ......${N}"
read -p "Enter your choice y/n:" choice
case $choice in
   y)
    echo "${B}${L}Enter user name that you want to enable autologin${N}"
    read -p "User name:" name
   sudo sed -i "3s/.*/autologin=$name/" "/etc/lxdm/lxdm.conf"
echo "${G}${L}[+] Enabled  ......${N}"
   ;;
   n)
   echo "${G}${L}[-] Disabled  ......${N}"
   ;;
esac

# Apache server
echo "${B}${L}[+] Do you want to enable apche server (For option 1 or 3)  ......${N}"
read -p "Enter your choice y/n:" choice
case $choice in
   y)
   sudo systemctl enable httpd
echo "${G}${L}[+] Enabled  ......${N}"
   ;;
   n)
   echo "${G}${L}[-] Disabled  ......${N}"
   ;;
esac

# fish shell
echo "${B}${L}[+] Do you want to Install fish shell  ......${N}"
read -p "Enter your choice y/n:" choice
case $choice in
   y)
   sudo pacman -S fish --noconfirm
    echo /usr/bin/fish | sudo tee -a /etc/shells
     chsh -s /usr/bin/fish
# fish greeting
sed -i '2c\echo Hello  $USER!' ~/.config/fish/config.fish
sed -i '3c\echo The time is (set_color yellow; date +%T; set_color normal) and you are using $hostname' ~/.config/fish/config.fish 

echo "${G}${L}[+] Enabled  ......${N}"
   ;;
   n)
   echo "${G}${L}[-] Disabled  ......${N}"
   ;;
esac
